language: php
php:
    - 7.3

before_script:
    - nvm install 11
    - npm install grunt-cli -g
    - npm install grunt

install:
    - scripts/download_jqueryui.sh
    - npm install
    - npm rebuild node-sass
    - composer install

script:
    - npm run-script build